server:
  #端口
  port: 8080

file.upload.path: E:\\image\

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 100000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 100000 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

  datasource:
    url: jdbc:mysql://localhost:3306/karelu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      #连接池名
      pool-name: Karelu
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 100000
      #从连接池返回的连接的自动提交
      auto-commit: true
      #连接的最大存活时间，0表示永久存活
      max-lifetime: 1800000
      #连接超时时间 30s
      connection-timeout: 30000
      #测试连接hi否可用的查询语句
      connection-test-query: SELECT 1

#mybatis-plus配置
mybatis-plus:
  #mapper映射文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.kmust.Karelu.entity
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false


#mybatis sql 打印( 方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.kmust.Karelu.mapper: debug

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: Karelu #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

rabbitmq:
  host: 10.1.188.178
  port: 5672
  username: guest
  password: guest
  virtual-host: /
  # 开启消息发送确认
  publisher-confirms: true
  publisher-returns: true
  listener:
    simple:
      acknowledge-mode: manual